version: "3"
services:
  content_image_optimization:
    image: "content_image_optimization"
    # pull_policy: always
    build: 
      context: .
      dockerfile: Dockerfile_cpu
    container_name: content_image_optimization
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports:
      - "5008:5008"
    environment:
      - SERVER_IP=192.168.40.172
      - PROCESS=content_image_optimization
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /path/to/project/content_image_optimization/api:/opt/api:rw
      - /var/log/images:/var/log/images:rw
    tty: true

