version: "3"
services:
  content_image_optimization:
    image: "content_image_optimization"
    # pull_policy: always
    build: 
      context: .
      dockerfile: Dockerfile_gpu
    container_name: content_image_optimization
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids:
              #   - MIG-ID-1
              #   - MIG-ID-2
              capabilities: [gpu]
    ports:
      - "5008:5008"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - SERVER_IP=103.42.50.120
      - PROCESS=image_enhancement
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /path/to/project/content_image_optimization/api:/opt/api:rw
      - /var/log/images/ml_models:/var/log/images/ml_models:rw
      - /path/to/project/image_enhancement:/path/to/project/image_enhancement:rw
    runtime: nvidia
    tty: true

